### ISSUE TITLE
Create panels for the MapMyRun info instead of using an iframe

### ISSUE THREAD

**Issue by spaceshiptrip** [spaceshiptrip/HikingHome#2]
To create a flexible `<div>` panel that contains a thumbnail image on the left, a bolded title on the right, and a description text underneath the title, we can use a combination of `flexbox` for layout and CSS for styling.

### Example HTML Structure:
```html
<div class="panel">
  <img src="thumbnail.jpg" alt="Thumbnail Image" class="panel-thumbnail">
  <div class="panel-content">
    <h4 class="panel-title">Panel Title</h4>
    <p class="panel-description">This is the description text under the title. It can contain additional details about the content in the panel.</p>
  </div>
</div>
```

### CSS for the Panel:
```css
/* Panel container */
.panel {
  display: flex; /* Flexbox for layout */
  align-items: flex-start; /* Align thumbnail and text content */
  margin: 10px 0; /* Margin around the panel */
  padding: 10px; /* Padding inside the panel */
  border: 1px solid #ddd; /* Optional border */
  border-radius: 8px; /* Rounded corners */
  max-width: 600px; /* Limit the width of the panel */
}

/* Thumbnail image */
.panel-thumbnail {
  width: 80px; /* Fixed width for thumbnail */
  height: 80px; /* Fixed height for thumbnail */
  object-fit: cover; /* Maintain aspect ratio */
  margin-right: 15px; /* Space between the thumbnail and content */
  border-radius: 5px; /* Optional: rounded corners for image */
}

/* Content container (title + description) */
.panel-content {
  display: flex;
  flex-direction: column;
}

/* Title */
.panel-title {
  font-size: 18px;
  font-weight: bold;
  margin: 0 0 5px 0; /* No margin on top, space below */
}

/* Description text */
.panel-description {
  font-size: 14px;
  margin: 0; /* No margin */
  color: #555; /* Slightly lighter color for description */
}
```

### Explanation:
- **`.panel`**: The container uses `flexbox` to align the thumbnail and text content in a row. You can place this anywhere in your HTML to create a panel.
- **`.panel-thumbnail`**: The thumbnail is a fixed-size image (80x80px by default). You can adjust this size as needed. The `object-fit: cover` ensures the image retains its aspect ratio.
- **`.panel-content`**: This container holds the title and description text, stacking them vertically using `flex-direction: column`.
- **`.panel-title`**: The title is bolded and slightly larger.
- **`.panel-description`**: The description is smaller and less prominent, appearing below the title.

### Example Usage:
You can use this panel anywhere in your HTML by repeating the structure with different images, titles, and descriptions:

```html
<div class="panel">
  <img src="path/to/thumbnail1.jpg" alt="Thumbnail 1" class="panel-thumbnail">
  <div class="panel-content">
    <h4 class="panel-title">First Panel Title</h4>
    <p class="panel-description">Some description for the first panel.</p>
  </div>
</div>

<div class="panel">
  <img src="path/to/thumbnail2.jpg" alt="Thumbnail 2" class="panel-thumbnail">
  <div class="panel-content">
    <h4 class="panel-title">Second Panel Title</h4>
    <p class="panel-description">Description for the second panel goes here.</p>
  </div>
</div>
```

This will create multiple panels with images, titles, and descriptions, all styled the same way and ready to be used flexibly throughout your layout.
